// Generated by https://quicktype.io

export interface A {
  data: Data;
}

export interface Data {
  pokemon_v2_type: PokemonV2Type[];
}

export interface PokemonV2Type {
  id:                        number;
  name:                      string;
  pokemon_v2_typeefficacies: PokemonV2TypeEfficacy[];
}

export interface PokemonV2TypeEfficacy {
  damage_factor:  number;
  target_type_id: number;
}
